Calculate std::abs(INT_MIN) without UB
Evidence for this comment:

+/// The return type is specified explicitly because with 'auto'
+/// gcc deduces it incorrectly in the accompanying unit test.

/opt/lmi/src/lmi/math_functions_test.cpp:567:32: \
  error: conversion from ‘int’ to ‘uint16_t’ \
  {aka ‘short unsigned int’} may change value [-Werror=conversion]
  567 |         std::uint16_t u = u_abs(j);
      |                           ~~~~~^~~