Prefer modern dialect
It's not necessarily obvious why the non-const std::string::data()
overload must return a contiguous, null-terminated C string. It's
contiguous because C++17 (N4659) [24.3.2.7.1/4] says it returns
| A pointer p such that
| p + i == &operator[](i) for each i in [0, size()]
; and it's null-terminated because that range includes its right
endpoint, and [24.3.2.5/2] operator[size()] returns charT(), which
equals zero.

Before C++17 added the non-const data() overload, some authors had
recommended '&s[0]' instead of 's.data()'. The latter seems better
for the same reason that 's.front()' is better than 's[0]'; moreover,
'&s[0]' has been reported to elicit compiler warnings where '&s[0U]'
does not.

It's worth mentioning that, while
    STARTUPINFO startup_info = {};
is fine, these alternatives:
    STARTUPINFO startup_info = {'\0'};
    STARTUPINFO startup_info = {0};
elicit diagnostics from gcc-7.2.0 with '-Wall -Wextra':
  error: missing initializer for member...
  [-Werror=missing-field-initializers]