Avoid error due to narrowing C++11 initialization with clang
This corrects

facets.cpp:118:50: error: constant expression evaluates to -8193 which
cannot be narrowed to type 'std::ctype_base::mask' (aka 'unsigned
short') [-Wc++11-narrowing]

when using clang by simply removing the braces, which impose C++11
initialization and forbidding narrowing, and allowing the implicit cast
to unsigned short to take place.