Fix 'set -e' issues
Explicitly allowed several commands to fail. Tested with redhat-7.7,
though not with debian-testing's new gcc-10.0.0 .

When 'yum' finds nothing to do, this command:
  yum --assumeyes install <package-name>
succeeds, incidentally reporting:
  Nothing to do
but this command:
  yum --assumeyes install <URL-for-rpm>
fails, reporting:
  Error: Nothing to do
Therefore, appended "|| true" only in the latter case.