Fix an observed problem
After rebuilding thus:
  $cd /opt/lmi/src/lmi
  $make eviscerate
  $rm -rf /opt/lmi/bin
  $logfile=log-`date -u +'%Y%m%dT%H%MZ'`; \
   echo "Log file is '$logfile.tar.xz'."; \
   ./install_msw.sh >$logfile 2>&1; \
   tar -cJf $logfile.tar.xz $logfile; mv ${logfile}* ..
  $git diff --no-index --color=always --color-moved=plain \
   ../log-20190519T1536Z ../log-20190519T2007Z \
   |sed -e's/^.\[3[12]m/&ZZZ/' |less -RS
the resulting log was observed to contain:
  Error: Nonce directory '/opt/lmi/zzz/mingw-ad_hoc/ad_hoc' already \
   exists.
  Probably it is left over from a previous failure.
  Just remove it unless you're sure you want whatever files
  it might contain.
  make: *** [install_mingw.make:114: initial_setup] Error 1
Therefore, made evisceration more severe (the rebuild would have
succeeded if '/opt/lmi/zzz' had been removed at the beginning)
and automatic (in the particular case of rebuilding in the lmi
source directory).

Added '/opt/lmi/bin/' to the list of directories to be eviscerated.
Do not store valuable files there, or twiddle their permissions so
that 'rm --force' cannot remove them.