Disable clang -Wdeprecated-copy warning in regex_iterator
This is necessary to avoid the following

boost/regex/v4/regex_iterator.hpp:74:35: error: definition of implicit
copy constructor for 'regex_iterator_implementation<...>' is deprecated
because it has a user-declared copy assignment operator

error when compiling Boost.Regex code with clang 10.